# Generated by Django 2.1.7 on 2019-05-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authro',
            new_name='author',
        ),
    ]
